Project-Trial
samif1/project-trial pull request #1
Opened 2022-11-07 21:49 UTC by samif1

In this projects:
   linters are added for the purpose of fixing.
   .gitignore file are added.
    index.html file is added for the webpage.
    style.css file is added for the stylesheet.

2022-11-07 21:56 UTC, samif1 commented on README.md
> -# project-trial
it would be better if your README file looks professional and contains details of your projects.

2022-11-07 21:59 UTC, samif1 commented on index.html
> +        <h2>Fast Shipping</h2>
for a title it would be better if you use h1 tag instead of h2

2022-11-07 22:07 UTC, samif1 reviewed
HI @samif1 
There are some issues that you still need to work but you are almost there!

**To Highlight**
You used the correct Github flow
Descriptive pull request message
Linter error checks validated
Documented your work professionally

**Required Changes**
check my comments bellow!

2022-11-07 22:07 UTC, samif1 commented on style.css
> +
please remove the comment for the purpose of clean code

2022-11-07 22:11 UTC, samif1 reviewed
HI @samif1
There are some issues that you still need to work but you are almost there!

To Highlight
You used the correct Github flow
Descriptive pull request message
Linter error checks validated
Documented your work professionally

Required Changes
check my comments bellow!

2022-11-07 22:11 UTC, samif1 commented on README.md
> -# project-trial
it would be better if you follow professional README,md file and your README.md should contain the details of your project.

2022-11-07 22:11 UTC, samif1 commented on index.html
> +        <h2>Premium Materials</h2>
for the title it would be better if you use h1 tags element instead of h2

2022-11-07 23:06 UTC, bienvenuushindi requested changes
## Hi @samif1 ,

Good job so far!

## Highlights!
:+1: Review contains at least 2 Inline comments :clap:


Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review and here 👇._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-07 23:06 UTC, bienvenuushindi commented on README.md
> -# project-trial
:red_circle: I think this comment will look great :100: if you include an explanation, a "why", for this change. In case you have any templates that reflect a professional :high_brightness:   README, Please make sure you share a link to it in your comment so that the reader can see what a professional README looks like. 

For example, You would say
**Your README file needs to be more descriptive. Kindly follow this [template](url_incase_you_have_one) and customize it to make your  README file looks professional . A well-crafted description allows you to show off your work to other developers as well as potential employers.**

- [ ] I think a better comment should always appear as a suggestion. **Note:**  "It would be better..." implies that if you don't do it in the way that's suggested, you are wrong. I think a better alternative to this could be "I think it would be better..."

2022-11-07 23:06 UTC, bienvenuushindi commented on README.md
> -# project-trial
:red_circle: Great job pointing out this issue. :art: However, asking for a professional README is too vague because there is no extra information about how to make it professional, also why this change should be implemented. Please, consider answering these questions :speech_balloon: Part of giving a good review is pointing out a clear reason to make the change. :robot: :hammer_and_wrench:. 

- [ ] I think a better comment should always appear as a suggestion. **Note:**  "It would be better..." implies that if you don't do it in the way that's suggested, you are wrong. I think a better alternative to this could be "I think it would be better..."

2022-11-07 23:16 UTC, bienvenuushindi commented on index.html
> +        <h2>Premium Materials</h2>
:red_circle: I think this comment will look great :100: if you include an explanation, "why" this change. Always remember that something might be clear to you but not to others.

- [ ] I think a better comment should always appear as a suggestion. This is a polite suggestion: "I think it would be better to use semantic h1 rather than h2" because .....

2022-11-07 23:18 UTC, bienvenuushindi commented on index.html
> +        <h1>Premium Materials</h1>
:red_circle: I think this comment will look great 100 if you include an explanation, of "why" this change. Always remember that something might be clear to you but not to others.

  I think a better comment should always appear as a suggestion. This is a polite suggestion: "I think it would be better to use semantic h1 rather than h2" because .....

2022-11-08 12:49 UTC, fherrerao approved these changes
# ✅  🎆  STATUS APPROVED! ✅ 🎆 
#
Hi @samif1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Great Job Yes GIF by Hollywood Suite](https://user-images.githubusercontent.com/91301423/197768588-bd30fde7-65cc-4249-9dd9-cc1fc1889a94.gif)


## Highlights
✔️  Excellent use of inline comments.
✔️  Polite comments.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 15:14 UTC, merged